"""add risk_verdict_reason to signals

Revision ID: 9afdbe3c723b
Revises: 96c24b14fafe
Create Date: 2026-08-25 16:17:03.636455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afdbe3c723b'
down_revision: Union[str, Sequence[str], None] = '96c24b14fafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('risk_verdict_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'risk_verdict_reason')
    # ### end Alembic commands ###
