"""add derivatives_snapshots table

Revision ID: a16a09ba6d99
Revises: b958ebd1a9d1
Create Date: 2026-08-26 22:56:25.293358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16a09ba6d99'
down_revision: Union[str, Sequence[str], None] = 'b958ebd1a9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivatives_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('long_short_ratio', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derivatives_snapshots')
    # ### end Alembic commands ###
