"""add retry_events and engine_heartbeats tables

Revision ID: b958ebd1a9d1
Revises: c6a1a51e0487
Create Date: 2026-08-26 02:05:36.642921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b958ebd1a9d1'
down_revision: Union[str, Sequence[str], None] = 'c6a1a51e0487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(length=50), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('request_desc', sa.String(length=200), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('delay_seconds', sa.Float(), nullable=False),
    sa.Column('exception_type', sa.String(length=100), nullable=False),
    sa.Column('exception_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retry_events')
    op.drop_table('engine_heartbeats')
    # ### end Alembic commands ###
