"""add human decision fields to signals, add paper_trades table

Revision ID: c6a1a51e0487
Revises: 9afdbe3c723b
Create Date: 2026-08-25 19:38:28.605167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a1a51e0487'
down_revision: Union[str, Sequence[str], None] = '9afdbe3c723b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('proposed_entry_price', sa.Float(), nullable=False),
    sa.Column('entry_fill_price', sa.Float(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='paper_trade_status'), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('proposed_exit_price', sa.Float(), nullable=True),
    sa.Column('exit_fill_price', sa.Float(), nullable=True),
    sa.Column('exit_fee', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('r_multiple_ideal', sa.Float(), nullable=True),
    sa.Column('r_multiple_realistic', sa.Float(), nullable=True),
    sa.Column('pnl_ngn', sa.Float(), nullable=True),
    sa.Column('approval_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.add_column('signals', sa.Column('triggering_candle_time', sa.DateTime(), nullable=False))
    # add_column (unlike create_table) does NOT auto-create the enum's
    # Postgres TYPE first -- create it explicitly or the ALTER TABLE fails
    # with "type human_decision does not exist".
    human_decision_enum = sa.Enum('APPROVED', 'DECLINED', name='human_decision')
    human_decision_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('signals', sa.Column('human_decision', human_decision_enum, nullable=True))
    op.add_column('signals', sa.Column('human_decision_reason', sa.Text(), nullable=True))
    op.add_column('signals', sa.Column('human_decision_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'human_decision_at')
    op.drop_column('signals', 'human_decision_reason')
    op.drop_column('signals', 'human_decision')
    sa.Enum(name='human_decision').drop(op.get_bind(), checkfirst=True)
    op.drop_column('signals', 'triggering_candle_time')
    op.drop_table('paper_trades')
    # ### end Alembic commands ###
